### ISSUE TITLE
hiera 5 compatibility

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-hiera#189]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.9.2
- Ruby: 2.1.9
- Distribution: Ubuntu trusty
- Module version: 2.4.0

## How to reproduce (e.g Puppet code you use)
```yaml
hiera::owner: root
hiera::group: root
hiera::backends:
  - yaml
  - file

hiera::backend_options:
  yaml:
    datadir: "/etc/puppetlabs/code/environments/%{literal('%')}{::environment}/hieradata"
  file:
    datadir: "/etc/puppetlabs/code/environments/%{literal('%')}{::environment}/hierafiles"

hiera::merge_behavior: deeper
hiera::hierarchy:
  - "fqdn/%{literal('%')}{::fqdn}"
  - "roles/%{literal('%')}{role}"
  - "vm_profiles/%{literal('%')}{vm_profile}"
  - "vm_parents/%{literal('%')}{vm_parent}"
  - "repos"
  - "tlsdata"
  - "users"
  - "common"
```
## What are you seeing
puppet is issuing the following error:
```
Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
   (in /etc/puppetlabs/puppet/hiera.yaml)
```

## What behaviour did you expect instead

as always, i would expect this to just magically work.

## Any additional information you'd like to impart

…however, there's currently *no* documentation on hiera5: https://tickets.puppetlabs.com/browse/HI-555
