### ISSUE TITLE
New hiera.yaml v5 format misses eyaml options

### ISSUE THREAD

**Issue by tmannerm** [voxpupuli/puppet-hiera#206]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.5 as included in  PE 2016.4.7
- Ruby: 2.1.9p490 as included in  PE 2016.4.7
- Distribution: CentOS 6.9
- Module version: 3.1.0

## How to reproduce (e.g Puppet code you use)

Update to v3.1.0 with "eyaml => true" in the manifest. Only added hiera_version and hiera5_defaults params and converted hierarchy as is to the new syntax (with only name and path keys).

## What are you seeing

Eyaml encryption is no longer working because options hash with private/public keys and required lookup_key are missing from the generated hiera.yaml v5 format.

## What behaviour did you expect instead

Eyaml encryption still working just like in the hiera.yaml v3 format.

## Any additional information you'd like to impart

I chose not to convert to environment specific hiera.yaml so I use this module to generate global hiera.yaml but just with new v5 format.

**Comment by elmobp** [comment]
Heya,

eyaml syntax has changed in v5 see my example below in hiera
```yaml
---
classes:
  - hiera

hiera::hiera_version: '5'
hiera::hiera5_defaults::datadir: 'data'
hiera::hiera5_defaults::data_hash: 'yaml_data'
hiera::manage_package: true
hiera::hierarchy:
  - name: 'trusted'
    path: 'nodes/%{::trusted.certname}'
    lookup_key: 'eyaml_lookup_key'
    options:
      pkcs7_private_key: /etc/puppetlabs/puppet/keys/private_key.pkcs7.pem
      pkcs7_public_key:  /etc/puppetlabs/puppet/keys/public_key.pkcs7.pem
      extension: yaml
```
Note: lookup_key and options
