### ISSUE TITLE
Using a hash for the template

### ISSUE THREAD

**Issue by pjfoley** [voxpupuli/puppet-hiera#21]
Hi,

I am looking to extend this module to setup hiera to use hiera-file.

Firstly I am new to ruby programming, which is causing me to stumble on trying to make this module a little bit more generic.  Essentially I am trying to work out a way to take a hash of values which can than be used within the template file to setup a range of hiera backends.

Here is how I have things setup so far:

I have a yaml file with this hash in it:

``` yaml

---
hiera::backends:
   yaml:
     datadir: '/root/dev/test'
   file:
     datadir: '/root/dev/foo'
   eyaml:
     datadir: '/root/dev/bar'
     pkcs7_private_key: '<%= @confdir %>/keys/private_key.pkcs7.pem'
     pkcs7_public_key: '<%= @confdir %>/keys/public_key.pkcs7.pem'
```

I than use hiera within puppet to pull the hash into a variable which the hiera.yaml.erg template will use:

``` erb
 ---
:backends:
 <%= @testing.keys.to_yaml.split("\n")[1..-1].join("\n") %>

 <%= @testing.to_yaml.split("\n")[1..-1].join("\n") %>
```

It almost seems to work

``` yaml

---
:backends:
   - yaml
   - file
   - eyaml

   yaml:.
     datadir: /root/dev/test
   file:.
     datadir: /root/dev/foo
   eyaml:.
     datadir: /root/dev/bar
     pkcs7_private_key: "<%= @confdir %>/keys/private_key.pkcs7.pem"
     pkcs7_public_key: "<%= @confdir %>/keys/public_key.pkcs7.pem"
```

As you can see from the generated yaml file, ruby does not prepend a ":" (colon) in front of the keys and it also has indented the first key's.

Does anyone have any ideas on how I can modify the behaviour of the .to_yaml function to prepend a colon and not have it indent?

Thanks,

Peter
